export default {
  "status": 1,
  "reason": "",
  "data": {
    "records": [
      {
        "id": 4924,
        "storyName": "技术优化：访客屏管理---》最后访问时间---》大于七天后自动删除，当前定时任务执行失败需进行优化",
        "businessName": null,
        "planName": null,
        "productName": null,
        "projectName": null,
        "projectId": 0,
        "source": {
          "key": "self_creation_optimize",
          "name": "自主自研(优化)"
        },
        "owner": "陈作镇",
        "type": null,
        "description": "<p>技术优化：访客屏管理---》最后访问时间---》大于七天后自动删除，当前定时任务执行失败需进行优化</p>",
        "createUser": "陈作镇",
        "createTime": "2023-08-16 18:04:46",
        "storyProgress": {
          "key": "under_taken",
          "name": "已承接"
        },
        "relatedName": "技术优化：访客屏管理---》最后访问时间---》大于七天后自动删除，当前定时任务执行失败需进行优化",
        "relatedId": 10500,
        "assignedTo": null,
        "assignedDate": null,
        "rejectedReason": null,
        "recipient": null,
        "collectionTime": null,
        "moduleName": null,
        "rejectedBy": null,
        "rejectionTime": null,
        "scheduledTime": null,
        "projectApprovalTime": null,
        "projectApprovalUser": null,
        "arraignTime": null,
        "closeReason": null,
        "closeUser": null,
        "closeTime": null,
        "estimateTestTime": null,
        "testUser": null,
        "testTime": null,
        "channel": {
          "key": "zentao-web",
          "name": "产研系统"
        },
        "demandValue": null,
        "sourceExplain": null,
        "competingGoodsContrast": null,
        "competingGoodsName": null,
        "goal": null,
        "goalExplain": null,
        "manHour": null,
        "clientCommunication": null,
        "companyId": 12704,
        "productOutPutStatus": null,
        "deliveryTime": ""
      },
      {
        "id": 4923,
        "storyName": "手机号码隐藏对表单无效",
        "businessName": null,
        "planName": null,
        "productName": null,
        "projectName": null,
        "projectId": 0,
        "source": {
          "key": "self_creation_optimize",
          "name": "自主自研(优化)"
        },
        "owner": "陈作镇",
        "type": null,
        "description": "<p>手机号码隐藏对表单无效</p>",
        "createUser": "陈作镇",
        "createTime": "2023-08-16 15:21:20",
        "storyProgress": {
          "key": "under_taken",
          "name": "已承接"
        },
        "relatedName": "手机号码隐藏对表单无效",
        "relatedId": 10499,
        "assignedTo": null,
        "assignedDate": null,
        "rejectedReason": null,
        "recipient": null,
        "collectionTime": null,
        "moduleName": null,
        "rejectedBy": null,
        "rejectionTime": null,
        "scheduledTime": null,
        "projectApprovalTime": null,
        "projectApprovalUser": null,
        "arraignTime": null,
        "closeReason": null,
        "closeUser": null,
        "closeTime": null,
        "estimateTestTime": null,
        "testUser": null,
        "testTime": null,
        "channel": {
          "key": "zentao-web",
          "name": "产研系统"
        },
        "demandValue": null,
        "sourceExplain": null,
        "competingGoodsContrast": null,
        "competingGoodsName": null,
        "goal": null,
        "goalExplain": null,
        "manHour": null,
        "clientCommunication": null,
        "companyId": 12704,
        "productOutPutStatus": null,
        "deliveryTime": ""
      },
      {
        "id": 4922,
        "storyName": "prd4环境数据统计，筛选项缺少ip去重",
        "businessName": null,
        "planName": null,
        "productName": null,
        "projectName": null,
        "projectId": 0,
        "source": {
          "key": "self_creation_optimize",
          "name": "自主自研(优化)"
        },
        "owner": "陈作镇",
        "type": null,
        "description": "<p><img src=\"http://kcall-test-oss.oss-cn-beijing.aliyuncs.com/12704/2023/8/16/f779e3405b554ab48e4e477d0031e51c.png\" alt=\"\" data-href=\"\" style=\"\"/></p>",
        "createUser": "陈作镇",
        "createTime": "2023-08-16 15:16:10",
        "storyProgress": {
          "key": "under_taken",
          "name": "已承接"
        },
        "relatedName": "prd4环境数据统计，筛选项缺少ip去重",
        "relatedId": 10498,
        "assignedTo": null,
        "assignedDate": null,
        "rejectedReason": null,
        "recipient": null,
        "collectionTime": null,
        "moduleName": null,
        "rejectedBy": null,
        "rejectionTime": null,
        "scheduledTime": null,
        "projectApprovalTime": null,
        "projectApprovalUser": null,
        "arraignTime": null,
        "closeReason": null,
        "closeUser": null,
        "closeTime": null,
        "estimateTestTime": null,
        "testUser": null,
        "testTime": null,
        "channel": {
          "key": "zentao-web",
          "name": "产研系统"
        },
        "demandValue": null,
        "sourceExplain": null,
        "competingGoodsContrast": null,
        "competingGoodsName": null,
        "goal": null,
        "goalExplain": null,
        "manHour": null,
        "clientCommunication": null,
        "companyId": 12704,
        "productOutPutStatus": null,
        "deliveryTime": ""
      },
      {
        "id": 4921,
        "storyName": "数据报表缺少名片数字段",
        "businessName": null,
        "planName": null,
        "productName": null,
        "projectName": null,
        "projectId": 0,
        "source": {
          "key": "business_dept",
          "name": "业务部门"
        },
        "owner": "陈作镇",
        "type": null,
        "description": "<p>接入分析所有的列表，新增名片数字段</p>",
        "createUser": "陈作镇",
        "createTime": "2023-08-16 15:13:00",
        "storyProgress": {
          "key": "under_taken",
          "name": "已承接"
        },
        "relatedName": "数据报表缺少名片数字段",
        "relatedId": 10497,
        "assignedTo": null,
        "assignedDate": null,
        "rejectedReason": null,
        "recipient": null,
        "collectionTime": null,
        "moduleName": null,
        "rejectedBy": null,
        "rejectionTime": null,
        "scheduledTime": null,
        "projectApprovalTime": null,
        "projectApprovalUser": null,
        "arraignTime": null,
        "closeReason": null,
        "closeUser": null,
        "closeTime": null,
        "estimateTestTime": null,
        "testUser": null,
        "testTime": null,
        "channel": {
          "key": "zentao-web",
          "name": "产研系统"
        },
        "demandValue": null,
        "sourceExplain": null,
        "competingGoodsContrast": null,
        "competingGoodsName": null,
        "goal": null,
        "goalExplain": null,
        "manHour": null,
        "clientCommunication": null,
        "companyId": 12704,
        "productOutPutStatus": null,
        "deliveryTime": ""
      },
      {
        "id": 4920,
        "storyName": "APP  我的客户 新增优化",
        "businessName": "APP  我的客户 新增优化",
        "planName": null,
        "productName": null,
        "projectName": null,
        "projectId": 0,
        "source": null,
        "owner": "张宇迪",
        "type": null,
        "description": "<p>分配客资， 会分给自己，但数据会到 默认公海，（不能用）</p><p>释放客资，会到指定公海，但是不会分给自己，（需要自己领取，多一步操作。慢了，有可能被别人领取）</p><p><br></p><p>这俩应该合并：创建给自己，并能指定公海</p><p><img src=\"http://kcall-test-oss.oss-cn-beijing.aliyuncs.com/12704/2023/8/15/50b163e46c4c40a7b369235653d6d583.png\" alt=\"\" data-href=\"\" style=\"\"/></p><p><br></p><p>新增数据 所在的 位置 太深， 如果我的客户模块没有，不能新增。应该任何情况都能新增，（电脑端如此）</p><p><br></p><p><img src=\"http://kcall-test-oss.oss-cn-beijing.aliyuncs.com/12704/2023/8/15/365222557b174a07bd27efe535073475.png\" alt=\"\" data-href=\"\" style=\"\"/></p>",
        "createUser": "肖海亮",
        "createTime": "2023-08-15 17:34:57",
        "storyProgress": {
          "key": "under_taken",
          "name": "已承接"
        },
        "relatedName": null,
        "relatedId": null,
        "assignedTo": null,
        "assignedDate": null,
        "rejectedReason": null,
        "recipient": null,
        "collectionTime": null,
        "moduleName": null,
        "rejectedBy": null,
        "rejectionTime": null,
        "scheduledTime": null,
        "projectApprovalTime": null,
        "projectApprovalUser": null,
        "arraignTime": null,
        "closeReason": null,
        "closeUser": null,
        "closeTime": null,
        "estimateTestTime": null,
        "testUser": null,
        "testTime": null,
        "channel": {
          "key": "zentao-web",
          "name": "产研系统"
        },
        "demandValue": null,
        "sourceExplain": null,
        "competingGoodsContrast": null,
        "competingGoodsName": null,
        "goal": null,
        "goalExplain": null,
        "manHour": null,
        "clientCommunication": null,
        "companyId": 12704,
        "productOutPutStatus": null,
        "deliveryTime": ""
      },
      {
        "id": 4919,
        "storyName": "客户需要在访客名片区域显示接待客服的名字",
        "businessName": "客户需要在访客名片区域显示接待客服的名字",
        "planName": null,
        "productName": null,
        "projectName": null,
        "projectId": 0,
        "source": null,
        "owner": "张议",
        "type": null,
        "description": "<p>N37530合肥华安脑科医院AI群2.0M &nbsp;客户需要在名片区域很清晰的查看到上次是哪个客服给访客做了信息备注 如附件所示 方便客户查询信息的</p>",
        "createUser": "郭鑫英",
        "createTime": "2023-08-15 17:04:51",
        "storyProgress": {
          "key": "under_taken",
          "name": "已承接"
        },
        "relatedName": null,
        "relatedId": null,
        "assignedTo": null,
        "assignedDate": null,
        "rejectedReason": null,
        "recipient": null,
        "collectionTime": null,
        "moduleName": null,
        "rejectedBy": null,
        "rejectionTime": null,
        "scheduledTime": null,
        "projectApprovalTime": null,
        "projectApprovalUser": null,
        "arraignTime": null,
        "closeReason": null,
        "closeUser": null,
        "closeTime": null,
        "estimateTestTime": null,
        "testUser": null,
        "testTime": null,
        "channel": {
          "key": "zentao-web",
          "name": "产研系统"
        },
        "demandValue": null,
        "sourceExplain": null,
        "competingGoodsContrast": null,
        "competingGoodsName": null,
        "goal": null,
        "goalExplain": null,
        "manHour": null,
        "clientCommunication": null,
        "companyId": 12704,
        "productOutPutStatus": null,
        "deliveryTime": ""
      },
      {
        "id": 4918,
        "storyName": "手机端可以登录",
        "businessName": "手机端可以登录",
        "planName": null,
        "productName": null,
        "projectName": null,
        "projectId": 0,
        "source": null,
        "owner": "马立炀",
        "type": null,
        "description": "<p>客户希望客户端可以用手机端登录</p>",
        "createUser": "徐娟娟",
        "createTime": "2023-08-14 18:38:34",
        "storyProgress": {
          "key": "under_taken",
          "name": "已承接"
        },
        "relatedName": null,
        "relatedId": null,
        "assignedTo": null,
        "assignedDate": null,
        "rejectedReason": null,
        "recipient": null,
        "collectionTime": null,
        "moduleName": null,
        "rejectedBy": null,
        "rejectionTime": null,
        "scheduledTime": null,
        "projectApprovalTime": null,
        "projectApprovalUser": null,
        "arraignTime": null,
        "closeReason": null,
        "closeUser": null,
        "closeTime": null,
        "estimateTestTime": null,
        "testUser": null,
        "testTime": null,
        "channel": {
          "key": "zentao-web",
          "name": "产研系统"
        },
        "demandValue": null,
        "sourceExplain": null,
        "competingGoodsContrast": null,
        "competingGoodsName": null,
        "goal": null,
        "goalExplain": null,
        "manHour": null,
        "clientCommunication": null,
        "companyId": 12704,
        "productOutPutStatus": null,
        "deliveryTime": ""
      },
      {
        "id": 4917,
        "storyName": "跟进模板由 管理员统一设置， 普通。部门管理，不能修改",
        "businessName": "跟进模板由 管理员统一设置， 普通。部门管理，不能修改",
        "planName": null,
        "productName": null,
        "projectName": null,
        "projectId": 0,
        "source": null,
        "owner": "张宇迪",
        "type": null,
        "description": "<p>跟进记录里的 字段选择， 管理员选定后，普通客服自动统一，普通客服，部门管理员，不能自行添加，删除</p><p><img src=\"http://kcall-test-oss.oss-cn-beijing.aliyuncs.com/12704/2023/8/14/ecebf688efe54c5fa7899d4d05679b19.png\" alt=\"\" data-href=\"\" style=\"\"/></p>",
        "createUser": "肖海亮",
        "createTime": "2023-08-14 18:24:46",
        "storyProgress": {
          "key": "under_taken",
          "name": "已承接"
        },
        "relatedName": null,
        "relatedId": null,
        "assignedTo": null,
        "assignedDate": null,
        "rejectedReason": null,
        "recipient": null,
        "collectionTime": null,
        "moduleName": null,
        "rejectedBy": null,
        "rejectionTime": null,
        "scheduledTime": null,
        "projectApprovalTime": null,
        "projectApprovalUser": null,
        "arraignTime": null,
        "closeReason": null,
        "closeUser": null,
        "closeTime": null,
        "estimateTestTime": null,
        "testUser": null,
        "testTime": null,
        "channel": {
          "key": "zentao-web",
          "name": "产研系统"
        },
        "demandValue": null,
        "sourceExplain": null,
        "competingGoodsContrast": null,
        "competingGoodsName": null,
        "goal": null,
        "goalExplain": null,
        "manHour": null,
        "clientCommunication": null,
        "companyId": 12704,
        "productOutPutStatus": null,
        "deliveryTime": ""
      },
      {
        "id": 4916,
        "storyName": "针对机器人话术逻辑设计中，不符合规定场景的访客信息，不让走兜底通用话术，而是提醒人工介入",
        "businessName": "针对机器人话术逻辑设计中，不符合规定场景的访客信息，不让走兜底通用话术，而是提醒人工介入",
        "planName": null,
        "productName": null,
        "projectName": null,
        "projectId": 0,
        "source": null,
        "owner": "康熙",
        "type": null,
        "description": "<p>针对机器人话术逻辑设计中，不符合场景的访客信息，不让走兜底通用话术，而是提醒人工介入</p>",
        "createUser": "杨红芳",
        "createTime": "2023-08-14 18:19:22",
        "storyProgress": {
          "key": "under_taken",
          "name": "已承接"
        },
        "relatedName": null,
        "relatedId": null,
        "assignedTo": null,
        "assignedDate": null,
        "rejectedReason": null,
        "recipient": null,
        "collectionTime": null,
        "moduleName": null,
        "rejectedBy": null,
        "rejectionTime": null,
        "scheduledTime": null,
        "projectApprovalTime": null,
        "projectApprovalUser": null,
        "arraignTime": null,
        "closeReason": null,
        "closeUser": null,
        "closeTime": null,
        "estimateTestTime": null,
        "testUser": null,
        "testTime": null,
        "channel": {
          "key": "zentao-web",
          "name": "产研系统"
        },
        "demandValue": null,
        "sourceExplain": null,
        "competingGoodsContrast": null,
        "competingGoodsName": null,
        "goal": null,
        "goalExplain": null,
        "manHour": null,
        "clientCommunication": null,
        "companyId": 12704,
        "productOutPutStatus": null,
        "deliveryTime": ""
      },
      {
        "id": 4915,
        "storyName": "【客户端】解决客户端机器人偶现不回复问题",
        "businessName": null,
        "planName": null,
        "productName": null,
        "projectName": null,
        "projectId": 0,
        "source": {
          "key": "business_dept",
          "name": "业务部门"
        },
        "owner": "张议",
        "type": null,
        "description": "<p> <a href=\"https://alidocs.dingtalk.com/i/nodes/r1R7q3QmWeN9xOpnH17LwwKYVxkXOEP2\" target=\"_blank\">https://alidocs.dingtalk.com/i/nodes/r1R7q3QmWeN9xOpnH17LwwKYVxkXOEP2</a> </p>",
        "createUser": "张议",
        "createTime": "2023-08-14 17:09:44",
        "storyProgress": {
          "key": "under_taken",
          "name": "已承接"
        },
        "relatedName": "【客户端】解决客户端机器人偶现不回复问题",
        "relatedId": 10496,
        "assignedTo": null,
        "assignedDate": null,
        "rejectedReason": null,
        "recipient": null,
        "collectionTime": null,
        "moduleName": null,
        "rejectedBy": null,
        "rejectionTime": null,
        "scheduledTime": null,
        "projectApprovalTime": null,
        "projectApprovalUser": null,
        "arraignTime": null,
        "closeReason": null,
        "closeUser": null,
        "closeTime": null,
        "estimateTestTime": null,
        "testUser": null,
        "testTime": null,
        "channel": {
          "key": "zentao-web",
          "name": "产研系统"
        },
        "demandValue": null,
        "sourceExplain": null,
        "competingGoodsContrast": null,
        "competingGoodsName": null,
        "goal": null,
        "goalExplain": null,
        "manHour": null,
        "clientCommunication": null,
        "companyId": 12704,
        "productOutPutStatus": null,
        "deliveryTime": ""
      },
      {
        "id": 4914,
        "storyName": "设置了声音提醒后，触发到两个条件的哈，都需要提醒",
        "businessName": "设置了声音提醒后，触发到两个条件的哈，都需要提醒",
        "planName": null,
        "productName": null,
        "projectName": null,
        "projectId": 0,
        "source": null,
        "owner": "陈作镇",
        "type": null,
        "description": "<p>目前客户端一个消息同时触发多条件的提示音的话,目前客户端逻辑只会提示一个条件的提示音 &nbsp;</p><p>客户设置了“同事新到一条消息”跟“监控他人保存名片成功/访客留成功”的消息提示。需要多个都触发，客户不会一直盯着电脑，所以需要声音的这种提示。</p><p><br></p><p><img src=\"http://kcall-test-oss.oss-cn-beijing.aliyuncs.com/12704/2023/8/14/39b6cb9aef3a43f18381080c69793c32.png\" alt=\"\" data-href=\"\" style=\"\"/></p>",
        "createUser": "胡代月",
        "createTime": "2023-08-14 14:43:32",
        "storyProgress": {
          "key": "under_taken",
          "name": "已承接"
        },
        "relatedName": null,
        "relatedId": null,
        "assignedTo": null,
        "assignedDate": null,
        "rejectedReason": null,
        "recipient": null,
        "collectionTime": null,
        "moduleName": null,
        "rejectedBy": null,
        "rejectionTime": null,
        "scheduledTime": null,
        "projectApprovalTime": null,
        "projectApprovalUser": null,
        "arraignTime": null,
        "closeReason": null,
        "closeUser": null,
        "closeTime": null,
        "estimateTestTime": null,
        "testUser": null,
        "testTime": null,
        "channel": {
          "key": "zentao-web",
          "name": "产研系统"
        },
        "demandValue": null,
        "sourceExplain": null,
        "competingGoodsContrast": null,
        "competingGoodsName": null,
        "goal": null,
        "goalExplain": null,
        "manHour": null,
        "clientCommunication": null,
        "companyId": 12704,
        "productOutPutStatus": null,
        "deliveryTime": ""
      },
      {
        "id": 4913,
        "storyName": "目前历史记录不完整，需求修复",
        "businessName": "目前历史记录不完整，需求修复",
        "planName": null,
        "productName": null,
        "projectName": null,
        "projectId": 0,
        "source": null,
        "owner": "张宇迪",
        "type": null,
        "description": "<p>历史记录里没有完整的记录 更改信息，要查哪个账号更改的，查不到</p><p><img src=\"http://kcall-test-oss.oss-cn-beijing.aliyuncs.com/12704/2023/8/14/4bd7f5389142485fbb0aecc1db9fd4e1.png\" alt=\"\" data-href=\"\" style=\"\"/></p><p><img src=\"http://kcall-test-oss.oss-cn-beijing.aliyuncs.com/12704/2023/8/14/f9d9745681b645009e820fa3ca1cc789.png\" alt=\"\" data-href=\"\" style=\"\"/></p>",
        "createUser": "肖海亮",
        "createTime": "2023-08-14 13:55:42",
        "storyProgress": {
          "key": "under_taken",
          "name": "已承接"
        },
        "relatedName": null,
        "relatedId": null,
        "assignedTo": null,
        "assignedDate": null,
        "rejectedReason": null,
        "recipient": null,
        "collectionTime": null,
        "moduleName": null,
        "rejectedBy": null,
        "rejectionTime": null,
        "scheduledTime": null,
        "projectApprovalTime": null,
        "projectApprovalUser": null,
        "arraignTime": null,
        "closeReason": null,
        "closeUser": null,
        "closeTime": null,
        "estimateTestTime": null,
        "testUser": null,
        "testTime": null,
        "channel": {
          "key": "zentao-web",
          "name": "产研系统"
        },
        "demandValue": null,
        "sourceExplain": null,
        "competingGoodsContrast": null,
        "competingGoodsName": null,
        "goal": null,
        "goalExplain": null,
        "manHour": null,
        "clientCommunication": null,
        "companyId": 12704,
        "productOutPutStatus": null,
        "deliveryTime": ""
      },
      {
        "id": 4912,
        "storyName": "抖开能力申请（用户手机号获取）",
        "businessName": null,
        "planName": null,
        "productName": null,
        "projectName": null,
        "projectId": 0,
        "source": {
          "key": "business_dept",
          "name": "业务部门"
        },
        "owner": "张宇迪",
        "type": null,
        "description": "<p>需求文档链接： <a href=\"https://alidocs.dingtalk.com/i/nodes/oP0MALyR8kZk3AbvU16zqRGXJ3bzYmDO?utm_scene=person_space\" target=\"_blank\">https://alidocs.dingtalk.com/i/nodes/oP0MALyR8kZk3AbvU16zqRGXJ3bzYmDO?utm_scene=person_space</a> </p><p>需求原型链接： <a href=\"https://nyiyq9.axshare.com\" target=\"_blank\">https://nyiyq9.axshare.com</a> </p>",
        "createUser": "张宇迪",
        "createTime": "2023-08-14 11:08:53",
        "storyProgress": {
          "key": "under_taken",
          "name": "已承接"
        },
        "relatedName": "抖开能力申请（用户手机号获取）",
        "relatedId": 10495,
        "assignedTo": null,
        "assignedDate": null,
        "rejectedReason": null,
        "recipient": null,
        "collectionTime": null,
        "moduleName": null,
        "rejectedBy": null,
        "rejectionTime": null,
        "scheduledTime": null,
        "projectApprovalTime": null,
        "projectApprovalUser": null,
        "arraignTime": null,
        "closeReason": null,
        "closeUser": null,
        "closeTime": null,
        "estimateTestTime": null,
        "testUser": null,
        "testTime": null,
        "channel": {
          "key": "zentao-web",
          "name": "产研系统"
        },
        "demandValue": null,
        "sourceExplain": null,
        "competingGoodsContrast": null,
        "competingGoodsName": null,
        "goal": null,
        "goalExplain": null,
        "manHour": null,
        "clientCommunication": null,
        "companyId": 12704,
        "productOutPutStatus": null,
        "deliveryTime": ""
      },
      {
        "id": 4911,
        "storyName": "oCPC文案问题",
        "businessName": null,
        "planName": null,
        "productName": null,
        "projectName": null,
        "projectId": 0,
        "source": {
          "key": "self_creation_optimize",
          "name": "自主自研(优化)"
        },
        "owner": "马立炀",
        "type": null,
        "description": "<p>oCPC文案问题统一改成小写o</p><p><img src=\"http://kcall-test-oss.oss-cn-beijing.aliyuncs.com/12704/2023/8/14/033ed805dad54f62974217aa3e4caa6e.png\" alt=\"\" data-href=\"\" style=\"\"/></p>",
        "createUser": "马立炀",
        "createTime": "2023-08-14 10:59:41",
        "storyProgress": {
          "key": "under_taken",
          "name": "已承接"
        },
        "relatedName": "oCPC文案问题",
        "relatedId": 10494,
        "assignedTo": null,
        "assignedDate": null,
        "rejectedReason": null,
        "recipient": null,
        "collectionTime": null,
        "moduleName": null,
        "rejectedBy": null,
        "rejectionTime": null,
        "scheduledTime": null,
        "projectApprovalTime": null,
        "projectApprovalUser": null,
        "arraignTime": null,
        "closeReason": null,
        "closeUser": null,
        "closeTime": null,
        "estimateTestTime": null,
        "testUser": null,
        "testTime": null,
        "channel": {
          "key": "zentao-web",
          "name": "产研系统"
        },
        "demandValue": null,
        "sourceExplain": null,
        "competingGoodsContrast": null,
        "competingGoodsName": null,
        "goal": null,
        "goalExplain": null,
        "manHour": null,
        "clientCommunication": null,
        "companyId": 12704,
        "productOutPutStatus": null,
        "deliveryTime": ""
      },
      {
        "id": 4910,
        "storyName": "inner-api 增加远程调用素材库获取菜单列表及详情列表",
        "businessName": null,
        "planName": null,
        "productName": null,
        "projectName": null,
        "projectId": 0,
        "source": {
          "key": "self_creation_optimize",
          "name": "自主自研(优化)"
        },
        "owner": "马立炀",
        "type": null,
        "description": "<table style=\"width: auto;\"><tbody><tr><td colSpan=\"1\" rowSpan=\"1\" width=\"auto\">inner-api 增加远程调用素材库获取菜单列表及详情列表</td></tr></tbody></table><p><br></p>",
        "createUser": "马立炀",
        "createTime": "2023-08-14 10:57:53",
        "storyProgress": {
          "key": "under_taken",
          "name": "已承接"
        },
        "relatedName": "inner-api 增加远程调用素材库获取菜单列表及详情列表",
        "relatedId": 10493,
        "assignedTo": null,
        "assignedDate": null,
        "rejectedReason": null,
        "recipient": null,
        "collectionTime": null,
        "moduleName": null,
        "rejectedBy": null,
        "rejectionTime": null,
        "scheduledTime": null,
        "projectApprovalTime": null,
        "projectApprovalUser": null,
        "arraignTime": null,
        "closeReason": null,
        "closeUser": null,
        "closeTime": null,
        "estimateTestTime": null,
        "testUser": null,
        "testTime": null,
        "channel": {
          "key": "zentao-web",
          "name": "产研系统"
        },
        "demandValue": null,
        "sourceExplain": null,
        "competingGoodsContrast": null,
        "competingGoodsName": null,
        "goal": null,
        "goalExplain": null,
        "manHour": null,
        "clientCommunication": null,
        "companyId": 12704,
        "productOutPutStatus": null,
        "deliveryTime": ""
      }
    ],
    "total": 3741,
    "size": 15,
    "current": 1,
    "orders": [],
    "optimizeCountSql": true,
    "hitCount": false,
    "countId": null,
    "maxLimit": null,
    "searchCount": true,
    "pages": 250
  }
}