export const list = [
    {
        "jnpfKey": "text",
        "title": "皇家福固智能科技有限公司设备展示",
        "color": "#888",
        "fontSize": "34px",
        "w": 552,
        "h": 68,
        "z": 10,
        "minW": 6,
        "minH": 4,
        "maxW": 12,
        "maxH": 6,
        "i": 100,
        "x": 274,
        "y": 14
    },
    {
        "jnpfKey": "video",
        "title": "摄像头现场",
        "w": 50,
        "h": 50,
        "z": 15,
        "src": "http://yjgl.lucheng.gov.cn:9223/live?port=9222&app=live&stream=test",
        "i": 101,
        "x": 1014,
        "y": 20,
        "fontSize": "NaNpx"
    },
    {
        "jnpfKey": "view",
        "title": "水位报警",
        "points": "1-WaterLevelAlarm",
        "unit": null,
        "eqp": "FGZN-COM1",
        "color": "#598ACF",
        "fontSize": "18px",
        "w": 266,
        "h": 50,
        "z": 10,
        "minW": 6,
        "minH": 4,
        "maxW": 12,
        "maxH": 6,
        "i": 105,
        "x": 306,
        "y": 138,
        "dataPoints": "正常"
    },
    {
        "jnpfKey": "view",
        "title": "水泵运行",
        "points": "1-PumpAlarm",
        "unit": null,
        "eqp": "FGZN-COM1",
        "color": "#598ACF",
        "fontSize": "18px",
        "w": 267,
        "h": 50,
        "z": 10,
        "minW": 6,
        "minH": 4,
        "maxW": 12,
        "maxH": 6,
        "i": 106,
        "x": 309,
        "y": 212,
        "dataPoints": "正常"
    },
    {
        "jnpfKey": "view",
        "title": "电源报警",
        "points": "1-PowerAlarm",
        "unit": null,
        "eqp": "FGZN-COM1",
        "color": "#598ACF",
        "fontSize": "18px",
        "w": 262,
        "h": 50,
        "z": 10,
        "minW": 6,
        "minH": 4,
        "maxW": 12,
        "maxH": 6,
        "i": 107,
        "x": 309,
        "y": 289,
        "dataPoints": "正常"
    },
    {
        "jnpfKey": "view",
        "title": "水位报警",
        "points": "2-WaterLevelAlarm",
        "unit": null,
        "eqp": "FGZN-COM1",
        "color": "#598ACF",
        "fontSize": "18px",
        "w": 242,
        "h": 50,
        "z": 10,
        "minW": 6,
        "minH": 4,
        "maxW": 12,
        "maxH": 6,
        "i": 110,
        "x": 861,
        "y": 216
    },
    {
        "jnpfKey": "view",
        "title": "水泵运行",
        "points": "2-PumpAlarm",
        "unit": null,
        "eqp": "FGZN-COM1",
        "color": "#598ACF",
        "fontSize": "18px",
        "w": 272,
        "h": 35,
        "z": 10,
        "minW": 6,
        "minH": 4,
        "maxW": 12,
        "maxH": 6,
        "i": 111,
        "x": 860,
        "y": 138
    },
    {
        "jnpfKey": "view",
        "title": "电源报警",
        "points": "2-PowerAlarm",
        "unit": null,
        "eqp": "FGZN-COM1",
        "color": "#598ACF",
        "fontSize": "18px",
        "w": 250,
        "h": 40,
        "z": 10,
        "minW": 6,
        "minH": 4,
        "maxW": 12,
        "maxH": 6,
        "i": 112,
        "x": 861,
        "y": 299
    },
    {
        "Name": "湿式一体机3",
        "ShortName": null,
        "DeviceNumber": 3,
        "EquPicture": [
            {
                "name": "th.jpg",
                "fileId": "th.jpg",
                "url": "/api/File/Image/annexpic/th.jpg"
            }
        ],
        "id": "433487686695649352",
        "parentId": "433487686695649349",
        "hasChildren": false,
        "children": null,
        "num": 0,
        "isLeaf": true,
        "icon": "icon-ym icon-ym-generator-notice",
        "jnpfKey": "img",
        "title": "湿式一体机3",
        "w": 269,
        "h": 211,
        "z": 5,
        "minW": 4,
        "minH": 7,
        "maxW": 12,
        "maxH": 7,
        "i": 113,
        "x": 13,
        "y": 414,
        "fontSize": "NaNpx",
        "titleShow": true
    },
    {
        "jnpfKey": "view",
        "title": "水位报警",
        "points": "3-WaterLevelAlarm",
        "unit": null,
        "eqp": "FGZN-COM1",
        "color": "#598ACF",
        "fontSize": "18px",
        "w": 272,
        "h": 50,
        "z": 10,
        "minW": 6,
        "minH": 4,
        "maxW": 12,
        "maxH": 6,
        "i": 115,
        "x": 301,
        "y": 497
    },
    {
        "jnpfKey": "view",
        "title": "水泵运行",
        "points": "3-PumpAlarm",
        "unit": null,
        "eqp": "FGZN-COM1",
        "color": "#598ACF",
        "fontSize": "18px",
        "w": 290,
        "h": 60,
        "z": 10,
        "minW": 6,
        "minH": 4,
        "maxW": 12,
        "maxH": 6,
        "i": 116,
        "x": 302,
        "y": 423
    },
    {
        "jnpfKey": "view",
        "title": "电源报警",
        "points": "3-PowerAlarm",
        "unit": null,
        "eqp": "FGZN-COM1",
        "color": "#598ACF",
        "fontSize": "18px",
        "w": 260,
        "h": 60,
        "z": 10,
        "minW": 6,
        "minH": 4,
        "maxW": 12,
        "maxH": 6,
        "i": 117,
        "x": 303,
        "y": 566
    },
    {
        "jnpfKey": "view",
        "title": "水位报警",
        "points": "4-WaterLevelAlarm",
        "unit": null,
        "eqp": "FGZN-COM1",
        "color": "#598ACF",
        "fontSize": "18px",
        "w": 250,
        "h": 50,
        "z": 10,
        "minW": 6,
        "minH": 4,
        "maxW": 12,
        "maxH": 6,
        "i": 118,
        "x": 870,
        "y": 489
    },
    {
        "jnpfKey": "view",
        "title": "水泵运行",
        "points": "4-PumpAlarm",
        "unit": null,
        "eqp": "FGZN-COM1",
        "color": "#598ACF",
        "fontSize": "18px",
        "w": 281,
        "h": 50,
        "z": 10,
        "minW": 6,
        "minH": 4,
        "maxW": 12,
        "maxH": 6,
        "i": 119,
        "x": 865,
        "y": 412
    },
    {
        "jnpfKey": "view",
        "title": "电源报警",
        "points": "4-PowerAlarm",
        "unit": null,
        "eqp": "FGZN-COM1",
        "color": "#598ACF",
        "fontSize": "18px",
        "w": 250,
        "h": 40,
        "z": 10,
        "minW": 6,
        "minH": 4,
        "maxW": 12,
        "maxH": 6,
        "i": 120,
        "x": 868,
        "y": 592
    },
    {
        "Name": "湿式一体机1",
        "ShortName": null,
        "DeviceNumber": 1,
        "EquPicture": [
            {
                "name": "th.jpg",
                "fileId": "th.jpg",
                "url": "/api/File/Image/annexpic/th.jpg"
            }
        ],
        "DeviceCode": "FGZN-COM1",
        "id": "438570188284100678",
        "parentId": "438570188284100677",
        "hasChildren": false,
        "children": null,
        "num": 0,
        "isLeaf": true,
        "icon": "icon-ym icon-ym-generator-notice",
        "jnpfKey": "img",
        "title": "湿式一体机1",
        "titleShow": true,
        "w": 269,
        "h": 211,
        "z": 5,
        "minW": 4,
        "minH": 7,
        "maxW": 12,
        "maxH": 7,
        "i": 122,
        "x": 13,
        "y": 141
    }
]